apiVersion: apps/v1
kind: Deployment
metadata:
  name: waha-integrator
  labels:
    app: waha-integrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waha-integrator
  template:
    metadata:
      labels:
        app: waha-integrator
    spec:
      containers:
        - name: app
          image: ghcr.io/jvizueta/ai-customer-service/waha-integrator:latest # kustomize will pin SHA in overlay
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: waha-integrator-secrets
            - configMapRef:
                name: waha-integrator-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi