apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - env.sealed.yaml
  - cloudflared-tunnel-token.sealed.yaml
  - cloudflared-cert.sealed.yaml
  - ../../base
images:
  - name: ghcr.io/jvizueta/ai-customer-service/counter-agent
    newTag: latest