apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - env.cluster.sealed.yaml
  - ../../base
images:
  - name: ghcr.io/jvizueta/ai-customer-service/waha-integrator
    newTag: dev-0efaecaeb35ae6dfb2d2cf2e4afcd63b722d85d9
