---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: waha-integrator-secrets
spec:
  encryptedData:
    WAHA_API_KEY: AgAO//Zdm09qQI+ufzPxBCyCt9hLeVKOd7yMY/8VsR12/Ch0Ob669dJDEsulk1/9xT2mF9sUZdmTtqtM4TtJyobPCTIt35y/7hBGZgqa4Htze9scg/CzXHh705qaovA9WjlYt4LLeoQnKBCrlXf/Iywg+eh652CcUCJFd3gduoUI5SA+q//ZReCLPdG83M4MpCxV3qkGfXSHr3OpdQs4oVJKSTBbJrTx5TpRYV5pf1dHySrRFbQBFOD3DfqRH9ECTrLgUqRH4KegN72/PSloY0xHON1IatHFxABYaPfu3UiimQpkEV7GfSZ7IUwOWTzrxeBmojiy+dhChlcqc5i0VdyiuXIHxW6D1kQBPfckHPsS/eVJrBJdXVDYKBMYQFKHM5iG+0LJvc8rtr8A2VvEBQgMTwaPld1XUQwlIxRcwCTLg1WMhbGRYv2CPtykl83aRV44D0LUoHD38JJotBFYqkTI4He6wzQltE7G1zWP04grEZGZRVVmgWRnOmgdP3XVa1vgwHHDqxZ8raGYnwaAGdjp8nVNXa+VwkbBjQcKGXC4O47iv6r6+7hDCy4m5bV9pQBahcgvHpEWK37nvUtyVA0airEORZtNYF3NgLfiAPVDdRa4lvS5YQNmqy/lO5iR3CzHIe4vthislQjil84qk99TNwT+XK2rz9+Lp145W/teZCISOintHEBO7CaNrepK04uhgSGZt6dwkmLi6c5IahUJf2VcmHzcgeRY6bxdL711UA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: waha-integrator-secrets
