---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: waha-integrator-secrets
spec:
  encryptedData:
    WAHA_API_KEY: AgADQ699YrkC/UmlciLcpLYBAbyoSZxbv+ZRfEpL7B8WHfXiiwYpgWvmRq9eCI14ySBHDiepoLyjWQGugV5ZccINjW6dxzOfKvbfhbfvr+eiIuAnzyYuzYkHkqBOiToNlFuvt+y7DoDJGWoExMW86cFyMy2tvkEyr4yct06gKO1fsHywDNI0hH6lWfmRJq3zlb7SEnGdK2wyYGJNyzoE1KLOiC6r3KooXQ9aILsIQMwpwmMTPL/9BnMEB/zVn2y46UNG+nDuIQ6jCntx4IDgcgOMWBRgEY7KAP74NCfcLsP4g63coY0rxf1JSQOO1xGFbftnB7iyWfpW8ru7FzeshY+dIzBDOzmS2BiaFLJ90sRoWHNF91YW0B8p1m41HcyQwoWbUcMvmZRf4rAbrH6asHT9slwg8oDB7K39CXoGu2xWFkVRr98abjIPDWJSXW7VxwbmOgVLb462S2dtHS3MFDZZbtgVCiZelWMFOTgEpqyFnVokrY2XEokHwt6KgUB7Vrrt3uVByPa+9qhxFOBOz6N1zWRlMDuUzfDwq6SHg3Sy/vavikPvpcRbN1v1vcFcM8inH5J9BeFNYGe5TO9WJvswQ5RvbpZSI8pcjcP+6Lyzvkt6X9msP6gluIaRn3S6E8gkO+FAoUbzqRpgerdodKeeuKEKnzTRKyLBquqCU1uLoeAswGYidGPmhS0jdiYD21YX3LU4RjDnjovLaC2ab0vjxxXdG4QgFLBIPrN7l1obOunKn38f+lJyvsTphTg6MFbpgAep2RQbmpUGLFaMG/reYFW//kWWaaA3AAcZek01tb4UwlN684rkJNkzdouIIfEhvpc5KUuGNs6wT5dcVpMvsi7TQXEEbsITf6M7AyeZE5rXlwPgaJM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: waha-integrator-secrets
