---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-cert
spec:
  encryptedData:
    cert.pem: AgAxkQyXt2tBU9VufG+JSXhD4cZkp0nk0c3kJq+HZSYqoAKiyp7KnAkXfC+y2mVBy2uTcn3PzZqSKsv7rfCLp/TxTrJHGI5w5O2HCAYF3W2IeejOFmy0zHaejkzz19J+LhclY9lm0+WmUi+gcE3luuaCpSmywpyRaWRzoJVnV6l8mGbrPHVD+RFgwLI+JTYVLwRik1n9fCK0OxF+y+1FjCG+lC+7LMe7cAHWbsXhSDO0nh+4i6oPUri24fe2rSNT4Dm2y86opZd+vPbRETMKKNVeTDBzPHiLHaleutwq7ia8C3nFrJbFqi0Bcqx1aUUDrlUBgmfTP2dmXQs6tbiNRmNluKluncDDTaVp6sVHp24VDLqnNxSoyGtG9hiA7Cv+Ly4RQ3k68fwWC2v5tweBuKl2t3cV4W7A2NQi1bd1E4rKeYNnHjKBLn1nA/y2vm4+RA/GPLTlH250nYaboCHbR5xUesucY2N+oQ7kmskICBCvI3/2jM2sf7dkpubuU//i30txR76+iAGzpHeLHSIw+s3KT/XNznB6CLb8rfii07yMQS7bIcyDE60tjjNuPgM3PhCFcWc+aI8Ry3agQkp9WmxKT1D4TWG1U236h4h30NUGY9L1PgSinO54Pa68wmImBvWfA7Lx7wzN/3gIrN77EXrcu6z1jLoCOp4t9cGN5kGSXNV13lTUovHs5SsK2LFnFKx2QBrB/5zZ5hSBv/4IyvtprVQYlkzUajAH5nyGEdPL05EYfqWrRMKNycCbbOdpHoC+6deO/Nbjf4F6FYT3QyJe10HHztji3gVbJWDLLW6k0GG5XkPX8d9GROemejL7NOxK+k1miC55HcPuhgwa1xGGusBtkNh/0XInRb0lYxp6C1m/d52OI1XJLARTCwn9B00Xc4CBvwTJd3x80Kq5J4Ft/TNHnsihMlpkNFWagQENFh2Si8eicMkNdM7dZ44v/7OY1f7/ynCMKXUZubNxGfZTgb2+PIm4edeikeBAfdQ91V1qjns5Em60vM+YWi86AAhakgXyy7wnMTHW0pPtL0LzHhqpfB+H9TWtpg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-cert
