---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: controller-manager
spec:
  encryptedData:
    credentials.json: AgAuOXDyjJsZyMfxyw+OQO1fHrsEb7c6vU96zsnNICMOvbJlFwKJoW7HG5YwrYmOMWWfXZ6o13aIiL4TlEHfH3UIHQsDvL5kvrr8Ez9Xj9863tCWuitiTOdxzlLUcBh4RAJZnZ8ZLuFmpfYeq2YEQ97GytknOw6BGIY+KMsKkAqQQj0Kkgyeo8sdtUjdm3xa6n8oDfJPIlOuFUzauFv35jOBky+7ze7Mbpsr1nmJcev2/FXAW7IJsYvrZ0IWuSsVFoJqUuNZ487KdqaedU7iDhhP5dNvDDrvGbeHsanrJFQDu2g3ad+3AsCnMq62Cx0X3bCMLAe1JohyyFJGCtIag3tkRx4LnJ0LdXiPyGFkw/dSWVkZ4fBMc0XelWNws/O8J1P6aOOYpwCMG4mN5vIa9Ru4pOx6SDOyX/PXnfM/oOR9GcLj8gXrWOV64fVHKBiQOc71rSVK/BqqjXvxMud+PbuhPzjz8rq1TpSl2nE6Soikb6qfjdifBm4yiXPggOEwTITN8dBBmFt2BB6f8lVAxStuwniwZ2s1XLImVBzBre0VtfTtk2GCHPaipRJJ2uknIVBZDdDqqbm2wx1sUl3kVtqxDUy5G6bkNJS7GN5oEAY495xDkZar0U1jQhp+fbcNiyx9PCoOlrOB7BR2wM85P5U2Wv5DiulXX6njn45qSLJL0Z9FCqg+mxhPEn0uzqy4UVyjR44AB4MaHkPyiBcjI65RAmJfQ4Y+OPTBoUTcmfDQw3w44Zq9+UHMRdyfz3nHqiysm+ecQe4ya04Yve95EBtQ8uqoT3eXLtJVfDbnBqz2PJEOEAqDEsmNJDUoUSJKIfrSplGOj0plsot0+O/ktB1FjHd+xtSHE4V+M7NQkY2uAkxhMTpqmwowSI+KfpiNTf6oGyMlEPvHstrMfQaonm6W1sZhKadv/VRYM6//dyMO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: controller-manager
