---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared-credentials
spec:
  encryptedData:
    credentials.json: AgAwtv2AGkXiCYFIcykJvhr4b+mo6oQSA0EfDA2DAEqvGYQ1Bo3b152gnnu8e/f3s/lmFl+bvgWshA9gAcgxeu5HrOMtA68ibI0xeGqpQF2DZ17u7UDR45quNU39sA/+RlIOFOB8oi9CZwb9fTD7dWCeE/7EF7MHZW1dXzwzJFlY9pSenDLrWNg9Iw01TzHO0IIEOeeig8i1Z38La/tqlzdkoWw3x3qjwHzct42hQANyV3/Jc2K1VbBGtqovPkQ5ZzAorTGepa6fwuH0qrtOEhRTXUMvQ3mYDzMwvmNlmseHrPuAXEPDeSxC8etxWM3wwOZgEI6hlLX/+7HjuwaLLSRpY6yOVpNc3KiT0LEl90BPWsrO8xC8IhEk3b8lhCNTsULg/NvMLKRltTqkn4AvVBcuVTtfWnV1br8aK3fagPMQ4dn3hWFfXzsqMyohkNJ0gm09+SLQnaH4cyYFXusFzfpD9eKF2IwRZWVJUeLXrxJ6UkycXlALH94YuESjNbWFZUDq/wlJQc6mquTjgNNpIUFOZOv4egaCkwBOskQ+TpF3s19QQArE9eWYIESPIbCXZY3vv4FT4bntWlNEvO5FE028w7wmOyv1QHB3FN7d75PkH1zS+vM+pJ5zC2/DmEUh9Oc27PPV4zKKslTWi/36jIUFqpI49//SIWudvdJUi7jKFRIA/gt34JLRyvtq7ASLguwQLZQ9TjPK/hL8GZd+8lU+NDZczUdIjZ6H6ZGRExjGVNrNYSWJjHM7ObsknWYBJxctrm6tVWYi8w9m+SzbQ9EbbME9kMa2wY7Zcf0tdN/dqg72SB9754gpRhjDYRjhXqNcWT2qDxlGBgLPDHQj0aYJhCzq9T2bnRqn3iIylAdGdGB8Pqj5fsGYONwo+deyGs9B9xse2Rd7bt5Sxwov20+lOCPf1jir1kHwaidgT0L0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared-credentials
